name: "Create coverage badge."
description: "It creates an svg badge to show a project coverage"
author: "Santiago Laza"

inputs:
  COVERAGE_REPORT:
    description: "Jest coverage report in Json format."
    required: true
  LABEL:
    description: "An optional label to set at the left of the percentage."
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
