name: "Create coverage badge."
description: "It creates an svg badge to show a project coverage"
author: "Santiago Laza"

inputs:
  COVERAGE_REPORT_PATH:
    description: "The path to the Jest coverage report in Json format."
    required: true
  LABEL:
    description: "An optional label to set at the left of the percentage."
    required: false
  BADGE_GENERATOR_SERVER_URL:
    description: "The server to generate badges, this action was build using shield.io. This value is in case we want to use our private server instead of the public."
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
