name: LMS Component deploy to PRODUCTION

on:
  workflow_call:
jobs:
  run:
    # Only deploy from main branch
    if: |
      !contains(github.ref, alpha) || !contains(github.ref, beta)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: caller_repository
    env:
      URL_LMS_API: https://portal.cell-ed.com
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_REGION: us-east-1
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          path: caller_repository

      - name: Checkout Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: Cell-Ed/workflows
          path: workflows_repository

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: ./workflows_repository/.github/processRepoName
        with:
          S3_BUCKET: celled-lms-prod
          REPO_NAME: ${{ github.event.repository.name }}
      - name: Check envs created.
        run: TAB_NAME=${{env.TAB_NAME}} WIDGET_NAME=${{ env.WIDGET_NAME}} REACT_APP_URL_BASE=${{env.REACT_APP_URL_BASE}} S3_BUCKET_DIRECTORY=${{env.S3_BUCKET_DIRECTORY}} BUILD_DIRECTORY=${{env.BUILD_DIRECTORY}}

      - uses: nimblehq/branch-tag-action@v1
        id: extract
      # Use the output/env from the `extract` step
      - name: Print the values
        run: |
          echo "The branch tag is ${{ steps.extract.outputs.branch_tag }}"
          echo "or ${{ env.BRANCH_TAG }}"
      - name: Get Branch
        run: |
          echo BRANCH=${{github.event.base_ref}}
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo ::set-env name=BRANCH::$branch
      - run: echo ${{ env.BRANCH }}
      - name: Validate alpha & beta version.
        uses: ./workflows_repository/.github/validateDependencies
        with:
          GITHUB_WORKSPACE: "caller_repository"

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.LMS_NPM_AUTOMATION_TOKEN}}" > .npmrc

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test ./ -- --coverage

      - name: Create Coverage Badge
        uses: ./workflows_repository/.github/createCoverageBadge
        with:
          COVERAGE_REPORT_PATH: "caller_repository/coverage/coverage-summary.json"
          LABEL: "Prod:"
          BADGE_GENERATOR_SERVER_URL: ${{ secrets.IMG_SHIELDS_GENERATOR_SERVER_URL }}

      - name: Deploy Coverage Badge
        uses: reggionick/s3-deploy@v3
        with:
          folder: workflows_repository/.github/createCoverageBadge/dist/badge
          bucket: celled-lms-docs/github-badges/prod/${{ env.S3_BUCKET_FOLDER }}
          bucket-region: ${{ env.S3_BUCKET_REGION }}
          "no-cache": true

      - name: Clean Coverage Badge Cache
        uses: ./workflows_repository/.github/cleanGithubImagesCache
        with:
          GH_TOKEN: ${{ secrets.SHIELDS_GH_TOKEN }}
          REPO_NAME: ${{ github.repository }}

      - name: Build
        run: CI=true npm run buildForJS

      - name: Deploy Micro-frontend
        uses: reggionick/s3-deploy@v3
        with:
          folder: caller_repository/${{env.BUILD_DIRECTORY}}
          bucket: ${{ env.S3_BUCKET_DIRECTORY }}
          bucket-region: ${{ env.S3_BUCKET_REGION }}

      - name: Update Directory List LMS
        uses: ./workflows_repository/.github/updateDirectoryListLMS
        with:
          URL_LMS_API: ${{ env.URL_LMS_API }}
          LMS_DIRECTORY_LIST_TOKEN: ${{ secrets.LMS_DIRECTORY_LIST_TOKEN }}
          TAB_NAME: ${{env.TAB_NAME }}
          WIDGET_NAME: ${{ env.WIDGET_NAME }}
