name: LMS Widget deploy to STAGING

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: caller_repository
    env:
      URL_LMS_API: https://staging-portal.cell-ed.com
      REACT_APP_API_ENDPOINT: ${{secrets.STAGING_API_ENDPOINT}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_REGION: us-east-1
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          path: caller_repository

      - name: Checkout Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: Cell-Ed/workflows
          path: workflows_repository

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: ./workflows_repository/.github/processRepoName
        with:
          S3_BUCKET: celled-lms-staging
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Check envs created.
        run: TAB_NAME=${{env.TAB_NAME}} WIDGET_NAME=${{ env.WIDGET_NAME}} REACT_APP_URL_BASE=${{env.REACT_APP_URL_BASE}} S3_BUCKET_DIRECTORY=${{env.S3_BUCKET_DIRECTORY}} BUILD_DIRECTORY=${{env.BUILD_DIRECTORY}}
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.LMS_NPM_AUTOMATION_TOKEN}}" > .npmrc

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test ./ -- --coverage

      - name: Create Coverage Badge
        uses: ./workflows_repository/.github/createCoverageBadge
        with:
          COVERAGE_REPORT_PATH: "caller_repository/coverage/coverage-summary.json"
          LABEL: "Test coverage:"

      - name: Deploy Coverage Badge
        uses: reggionick/s3-deploy@v3
        with:
          folder: workflows_repository/.github/createCoverageBadge/dist/badge
          bucket: celled-lms-docs/github-badges/staging/${{ env.S3_BUCKET_FOLDER }}
          bucket-region: ${{ env.S3_BUCKET_REGION }}

      - name: Build
        run: CI=true npm run build

      - name: Deploy Micro-frontend
        uses: reggionick/s3-deploy@v3
        with:
          folder: caller_repository/${{env.BUILD_DIRECTORY}}
          bucket: ${{ env.S3_BUCKET_DIRECTORY }}
          bucket-region: ${{ env.S3_BUCKET_REGION }}

      - name: Update Directory List LMS
        uses: ./workflows_repository/.github/updateDirectoryListLMS
        with:
          URL_LMS_API: ${{ env.URL_LMS_API }}
          LMS_DIRECTORY_LIST_TOKEN: ${{ secrets.LMS_DIRECTORY_LIST_TOKEN }}
          TAB_NAME: ${{env.TAB_NAME }}
          WIDGET_NAME: ${{ env.WIDGET_NAME }}
