name: LMS Component PUBLISH on NPM

on:
  workflow_call:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: caller_repository
    env:
      URL_LMS_API: https://portal.cell-ed.com
      REACT_APP_API_ENDPOINT: ${{ secrets.PROD_API_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_REGION: us-east-1
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          path: caller_repository

      - name: Checkout Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: Cell-Ed/workflows
          path: workflows_repository
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: https://registry.npmjs.org/

      - name: Process Repository Name
        uses: ./workflows_repository/.github/processRepoName
        with:
          S3_BUCKET: celled-lms-dev
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Validate alpha & beta version.
        uses: ./workflows_repository/.github/validateDependencies
        with:
          GITHUB_WORKSPACE: caller_repository

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.LMS_NPM_AUTOMATION_TOKEN}}" > .npmrc

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Prepare package
        run: CI=true npm run buildComponent

      - name: Publishing package
        run: |
          CANDIDATE_VERSION=$(node -p "require('./package.json').version");
          echo Candidate version: $CANDIDATE_VERSION;
          if [[ $CANDIDATE_VERSION == *"alpha"* ]];
          then
              echo "Alpha version detected";
              echo "Publishing alpha version";
              npm publish --tag alpha;
          elif [[ $CANDIDATE_VERSION == *"beta"* ]];
          then
              echo "Beta version detected";
              echo "Publishing beta version";
              npm publish --tag beta
          else
              echo "Production version detected";
              echo "Publishing production version";
              npm publish;
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.LMS_NPM_PUBLISH_TOKEN}}
