name: LMS Component deploy to DEVELOP

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: caller_repository
    env:
      REACT_APP_API_ENDPOINT: ${{secrets.DEV_API_ENDPOINT}}
      URL_LMS_API: https://dev-portal.cell-ed.com
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_REGION: us-east-1
      SHIELDS_IMAGE_URL: ghcr.io/badges/shields:next
      SHIELDS_HOST_PORT: 15080
      SHIELDS_CONTAINER_PORT: 8080
      SHIELDS_URL: http://localhost:15080      
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          path: caller_repository

      - name: Checkout Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: Cell-Ed/workflows
          path: workflows_repository
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Process Repository Name
        uses: ./workflows_repository/.github/processRepoName
        with:
          S3_BUCKET: celled-lms-dev
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Check envs created.
        run: TAB_NAME=${{env.TAB_NAME}} WIDGET_NAME=${{ env.WIDGET_NAME}}  S3_BUCKET_DIRECTORY=${{env.S3_BUCKET_DIRECTORY}} BUILD_DIRECTORY=${{env.BUILD_DIRECTORY}}

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.LMS_NPM_AUTOMATION_TOKEN}}" > .npmrc

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test ./ -- --coverage

      - name: Start shields.io Server
        run: |
          docker run -d -p ${{ env.SHIELDS_HOST_PORT }}:${{ env.SHIELDS_CONTAINER_PORT }} --env PORT=${{ env.SHIELDS_CONTAINER_PORT }} --name shields ${{ env.SHIELDS_IMAGE_URL }}
          until curl -s ${{ env.SHIELDS_URL }} > /dev/null; do
            echo "Waiting for container to be ready..."
            sleep 1
          done
          echo "Shields.io container is ready!"

      - name: Create Coverage Badge
        uses: ./workflows_repository/.github/createCoverageBadge
        with:
          COVERAGE_REPORT_PATH: "caller_repository/coverage/coverage-summary.json"
          LABEL: "Develop:"
          BADGE_GENERATOR_SERVER_URL: ${{ secrets.IMG_SHIELDS_GENERATOR_SERVER_URL }}

      - name: Deploy Coverage Badge
        uses: reggionick/s3-deploy@v3
        with:
          folder: workflows_repository/.github/createCoverageBadge/dist/badge
          bucket: celled-lms-docs/github-badges/dev/${{ env.S3_BUCKET_FOLDER }}
          bucket-region: ${{ env.S3_BUCKET_REGION }}
          "no-cache": true

      - name: Clean Coverage Badge Cache
        uses: ./workflows_repository/.github/cleanGithubImagesCache
        with:
          GH_TOKEN: ${{ secrets.SHIELDS_GH_TOKEN }}
          REPO_NAME: ${{ github.repository }}

      - name: Build
        run: CI=true npm run buildForJS

      - name: Deploy Micro-frontend
        uses: reggionick/s3-deploy@v3
        with:
          folder: caller_repository/${{env.BUILD_DIRECTORY}}
          bucket: ${{ env.S3_BUCKET_DIRECTORY }}
          bucket-region: ${{ env.S3_BUCKET_REGION }}

      - name: Update Directory List LMS
        uses: ./workflows_repository/.github/updateDirectoryListLMS
        with:
          URL_LMS_API: ${{ env.URL_LMS_API }}
          LMS_DIRECTORY_LIST_TOKEN: ${{ secrets.LMS_DIRECTORY_LIST_TOKEN }}
          TAB_NAME: ${{env.TAB_NAME }}
          WIDGET_NAME: ${{ env.WIDGET_NAME }}