name: Micro-service deploy to Develop

on:
  workflow_call:

env:
  APP_ENV: dev

jobs:
  func-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: caller_repository
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BADGES_BUCKET_REGION: us-east-1
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          path: caller_repository

      - name: Checkout Workflows Repository
        uses: actions/checkout@v4
        with:
          repository: Cell-Ed/workflows
          path: workflows_repository

      - name: Checkout Templates Repository
        uses: actions/checkout@v4
        with:
          repository: Cell-Ed/openfaas-templates
          path: repo-templates
          token: ${{ secrets.ACTIONS_CI_CD_ACCESS_TOKEN }}
          ref: main

      - run: |
          ls -a
          cp -r ../repo-templates/template ./template
          rm -rf ../repo-templates

      - name: Define ENV VARS
        id: define_env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_OUTPUT

      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 7.0.14
          mongodb-replica-set: rs0

      - name: Install mongoTools
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_CI_CD_ACCESS_TOKEN}}" > .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Debug
        run: |
          pwd
          ls -lta
          cat package.json

      - name: Create Config File
        uses: ./workflows_repository/.github/createServicesConfigFile
        with:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Run Unit Tests
        run: npm test ./ -- --coverage

      - name: Start shields.io Server
        run: |
          docker run -d -p 15080:8080 --env PORT=8080 --name shields ghcr.io/badges/shields:next
          until curl -s http://localhost:15080 > /dev/null; do
            echo "Waiting for container to be ready..."
            sleep 1
          done
          echo "Container is ready!"

      - name: Create Coverage Badge
        uses: ./workflows_repository/.github/createCoverageBadge
        with:
          COVERAGE_REPORT_PATH: "caller_repository/coverage/coverage-summary.json"
          LABEL: "Develop:"
          BADGE_GENERATOR_SERVER_URL: ${{ secrets.IMG_SHIELDS_GENERATOR_SERVER_URL }}

      - name: Deploy Coverage Badge
        uses: reggionick/s3-deploy@v4
        with:
          folder: workflows_repository/.github/createCoverageBadge/dist/badge
          bucket: micro-services-docs/github-badges/dev/${{ env.SERVICE_NAME }}
          bucket-region: ${{ env.S3_BADGES_BUCKET_REGION }}
          "no-cache": true

      - name: Clean Coverage Badge Cache
        uses: ./workflows_repository/.github/cleanGithubImagesCache
        with:
          GH_TOKEN: ${{ secrets.SHIELDS_GH_TOKEN }}
          REPO_NAME: ${{ github.repository }}

      - name: Create .env File if Exists
        run: |
          if [ -f ".env.$APP_ENV" ]; then
            mv -f ".env.$APP_ENV" .env
            rm -f .env.*
            cat .env
          fi     

      - name: Run shrinkwrap build
        run: |
          faas-cli build -f ./${{ env.SERVICE_NAME }}.yml \
          --build-arg NPM_AUTH_TOKEN=${{ secrets.NPM_CI_CD_ACCESS_TOKEN }} --shrinkwrap

      - name: Login to OpenFaaS Gateway
        run: |
          faas-cli login -p ${{ secrets.OPENFAAS_GATEWAY_DEV_PASSWD }} \
          -g ${{ secrets.OPENFAAS_GATEWAY_DEV }}

      - name: Login to DockerHub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push the OpenFaaS function
        uses: docker/build-push-action@v6
        with:
          context: caller_repository/build/${{ env.SERVICE_NAME }}/
          file: caller_repository/build/${{ env.SERVICE_NAME }}/Dockerfile
          push: true
          tags: celled/${{ env.SERVICE_NAME }}:latest-${{ steps.define_env.outputs.GITHUB_SHA_SHORT }}
          build-args: |
            NPM_AUTH_TOKEN=${{ secrets.NPM_CI_CD_ACCESS_TOKEN }}

      - name: Deploy the function
        run: |
          faas-cli deploy -f ./${{ env.SERVICE_NAME }}.yml --tag sha --gateway ${{ secrets.OPENFAAS_GATEWAY_DEV }}
        env:
          DOCKER_USER: celled
